### ISSUE TITLE
Confusion with original title

### ISSUE THREAD

**Issue by FRWo** [Portugao/MUFiles#33]
1. Uploading a file: "test.pdf" and call it with title: "1.Upload" -> file is stored as test.pdf
2. Uploading another file: "test.pdf" and call it : "2.Upload" -> file is stored as test2.pdf

so far so good

I want to download the 2nd file and MUFiles will download it as "test2.pdf" althought it should be "test.pdf"  as it is the name of the original file

**Comment by Portugao** [comment]
No, if you upload the same file twice the second get renamed.

**Comment by Portugao** [comment]
That is the logic at the moment.

**Comment by FRWo** [comment]
it's just we often have different files with similar names in different collections. So for my opinion  the name after downloading should be the same as it has been during the upload.

**Comment by Portugao** [comment]
Yes, I understand. How it was ruled in Downloads?

**Comment by FRWo** [comment]
I think, the original filename was stored  seperatly in the DB, but in the Download module from craigh who made it work for zik. 1.3.x there is an error while uploading a file with the same name. (it wont rename, it will delete the existing file), so I cannot test it.

And I don't have an old Download module with the full functionality working

**Comment by Portugao** [comment]
@FRWo 
Should be fixed.
