### ISSUE TITLE
show the child collections as a child

### ISSUE THREAD

**Issue by FRWo** [Portugao/MUFiles#34]
It would be nice to see the child collection as a child of its parent while doing a new Upload.
At the momnet I can see only all collections who seemed to have the same priority (in collection list in edit.tpl

**Comment by Portugao** [comment]
I have problems to understand your wish....

**Comment by FRWo** [comment]
While uploading a file, I could choose the right collection, the file has to be in.
At the moment, if I have collection like:
A (as parent)
1 (as child from A)
B (as parent)
1 (as child from B)

the listfield in the uploadtemplate will show me:
A
1
B
1

I would prefer a list like:
A
A - 1
B
B - 1

or something like a tree, so it is clear, to whom the child "1" will concern.

**Comment by Portugao** [comment]
Ok. I understand. Have to look....

**Comment by Portugao** [comment]
Do you need this also for the edit template creating or editing a collection?

**Comment by FRWo** [comment]
It would be great

**Comment by Portugao** [comment]
I'm asking me what about collections, that are deeper in the structure.
I think it could be a very complicated thing.

**Comment by Portugao** [comment]
@FRWo

**Comment by FRWo** [comment]
In our Intranet it is used to the third level:

Collection -> child -> child

f.e.: Fachliches -> Protokolle -> Jahr 2016

not going deeper.

**Comment by Portugao** [comment]
I will try.

**Comment by FRWo** [comment]
Anything new with showing the different levels?

**Comment by Portugao** [comment]
Hi Frank,
It works for collections but not for files now.
Hope to complete it in few days.
Greetings Michael Montag, 17 Oktober 2016, 08:31vorm. +0200 von Frank  notifications@github.com :

**Comment by FRWo** [comment]
Thx!

**Comment by Portugao** [comment]
@FRWo 
Please check the actual repository and give me a feedback, Frank.

Thx.

**Comment by Portugao** [comment]
@FRWo 
Does it work?

**Comment by FRWo** [comment]
Sorry, catched a cold...
it works for nearly 90%, I send you a mail.

**Comment by Portugao** [comment]
Thx for your mail.
I can reproduce the editing issue.

What a about the quick navigation? That's a new feature....

**Comment by FRWo** [comment]
It would be consistent, but at the moment it would be a "nice to have" feature

**Comment by Portugao** [comment]
Ok.
See #36

**Comment by Portugao** [comment]
@FRWo 
Please check again; should also work now for files with children collection...

**Comment by FRWo** [comment]
While editing an file with child collection now it shows all possible collections and not only the related ones.
F.E.: Correct would be: Kiel -> Protokolle -> Jahr 2016
At the moment it shows something like: Kiel-> ...-> Jahr 2009 -> Jahr 2010 -> Jahr 2011 -> Jahr 2012 a.s.o.

**Comment by Portugao** [comment]
I do not understand, I think...

**Comment by Portugao** [comment]
You have 3 levels and not more, correct?

**Comment by Portugao** [comment]
@FRWo 
Ok. I see. Very strange.... I will have a look.

**Comment by FRWo** [comment]
Yes, normally I have maximum of 3 levels.
At the moment there is only one collection with 4 levels, but this could be corrected if neccessary

**Comment by Portugao** [comment]
@FRWo 
I had a look again and I hope it works now like expected.

**Comment by Portugao** [comment]
@FRWo 
Sorry. There is something wrong again....It seems very complicated....

**Comment by Portugao** [comment]
@FRWo 
Very tricky for me. Now it should work. Please have a look when you have time.

**Comment by Portugao** [comment]
@FRWo 
Please check again!

**Comment by FRWo** [comment]
it seems, it works great - thank you!
For me we can close this ticket.

**Comment by Portugao** [comment]
Oh yes. I'm happy to read this. That was not so easy.....
Don't be shy to make further feature requests. The one with the quick nav is my mind............
